services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - app_data:/app
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    depends_on:
      - db
    networks: # added networks
      - backend

  db:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    networks:
      - backend

# added networks
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  app_data:
